# Похож на секреты, но его можно подкладывать внутрь пода (примонитровать в контейнер)
# Используется для прокидывания конфигурации (для всего, что конфигурируется не env-ами, а конфиг файлами) внутрь пода

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  key: value
