apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  {{ .Values.app.name }}-deployment
  # namespace: my-namespace
spec:
  replicas: {{ .Values.app.replicas }}
  selector:  
    matchLabels:
      components: {{ .Values.app.components }}
  template: 
    metadata:
      labels: #нужны для связи пода с Service (у нас будет NodePort)
        components: {{ .Values.app.components }}
    spec: 
      containers:
        - name:  {{ .Values.app.name }}
          image:  "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports: # указываем порты, которые должны быть прокинуты из контейнера в под
            - containerPort: {{ .Values.app.port }}
          resources: # допустимые лимиты на контейнер
            limits: {{ .Values.app.limits | toYaml | nindent 14 }} # Указываем, что нужно преобразовать в yaml и указываем кол-во отступов с помощью nindent
      