# Похож на секреты, но его можно подкладывать внутрь пода (примонитровать в контейнер)
# Используется для прокидывания конфигурации (для всего, что конфигурируется не env-ами, а конфиг файлами) внутрь пода

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  key: {{ .Release.Name }}
  # name: {{ upper .Values.name }} # делаем uppercase с помощью функции upper
  name: {{ .Values.name | upper | quote }}
  chart: {{ .Chart.AppVersion | quote }} # оборачиваем значение в кавычки с помощью функции quote
  date: {{ now | date "2006-01-02" | quote }} # через оператор pipeline (|) описываем, какие функции хотим применить к переменной