# Похож на секреты, но его можно подкладывать внутрь пода (примонитровать в контейнер)
# Используется для прокидывания конфигурации (для всего, что конфигурируется не env-ами, а конфиг файлами) внутрь пода

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  name: {{ .Values.app.version | toString | upper | quote }}
  
  # # if-else
  {{- if eq .Values.env "production"}}
  paymentToken: "1234"
  {{- else }}
  paymentToken: false
  {{- end }} # добавляем - чтобы не было пустых строк в итоговом манифесте



  # # with
  # memory: {{ .Values.value.requirements.limits.memory }}
  # cpu: {{ .Values.value.requirements.limits.cpu }}
  # # С помощью with даем указание искать значения в определенном свойстве
  {{- with .Values.value.requirements.limits }}
  memory: {{ .memory }}
  cpu: {{ .cpu }}
  version: {{ $.Values.app.version }} # Если нужно обратиться к самому корню в блоке with
  {{- end }}



  # # range
  users:
    {{- range $index, $user := .Values.users}} # указываем по какому массиву итерируемся 
    - {{  $user.name }}: "[{{ $index }}] {{ $user.role }}" # чтобы обратиться к элементу на текущей итерации используется . (или переменные)
    {{- end }}




# # переменные  
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
