apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clusterip
spec: 
  type: ClusterIP
  ports: 
    - port: {{ .Values.postgres.port }} # Если без targetPort, то targetPort = port
      protocol: TCP
  selector: 
    components: {{ .Values.postgres.components }}
