apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
type: Opaque
data:
  POSTGRES_DB: {{  .Values.database.db | b64enc | quote }}
  POSTGRES_USER: {{  .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{  .Values.database.password | b64enc | quote }}


# postgresql://user:password@url:5432/db
# postgresql://demo:demo@postgres-clusterip:5432/demo